name: squarestream
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4240313090849668
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#bfbfbf'
    - '#f98105'
    - '#454545'
  brandStrength: 0.25
  lightness: 0.4289598702453077
  saturation: 0.39095682045444846
  rhythmicContrast: 0.8655380494892597
purpose: []
