name: squarestream
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0
color:
  saturation: 0.3909568204544485
  brandStrength: 0.25
  rhythmicContrast: 0.8655380494892597
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#bfbfbf'
    - '#f98105'
    - '#454545'
  lightness: 0.4289598702453077
purpose: []
cta:
  bucket: null
  version: null
  domain: null
favicon: null
typography_spectrum: 0.516129
analytics:
  twitter: null
  google: null
  facebook: null
